### PR TITLE
travis builds should use dmd, ldc, and gdc. on multiple platforms

### PR DESCRIPTION
**Pull request by SingingBush**
this is the quickest way to ensure that the project works with various os & compiler combinations

### CODE REVIEW

**Comment by SingingBush** [comment]
The OSX builds currently fail:

```bash
Undefined symbols for architecture x86_64:
  "_sqlite3_column_database_name", referenced from:     _D4ddbc7drivers10sqliteddbc23SQLITEPreparedStatement14createMetadataMFZC4ddbc4core17ResultSetMetaData in ddbc-tests.o
  "_sqlite3_column_origin_name", referenced from:     _D4ddbc7drivers10sqliteddbc23SQLITEPreparedStatement14createMetadataMFZC4ddbc4core17ResultSetMetaData in ddbc-tests.o
  "_sqlite3_column_table_name", referenced from:     _D4ddbc7drivers10sqliteddbc23SQLITEPreparedStatement14createMetadataMFZC4ddbc4core17ResultSetMetaData in ddbc-tests.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

once this gets resolved the line that allows osx builds to fail should be removed from `.travis.yml`

**Comment by SingingBush** [comment]
thanks for merging the changes. I think until the OSX travis problem is resolved it may be worth putting `- os: osx` back under _allow\_failures_. Also, the before install part should probably be changed to run a `brew update` prior to installing sqlite:

```yml
before_install:
- "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew update && brew install sqlite && brew link --force sqlite; fi"
```

I've started doing a _unittest-cov_ build in [my project](https://github.com/SingingBush/eloquent) which should push the results to [coveralls.io](https://coveralls.io/github/SingingBush/eloquent?branch=master). Not sure if that's something you may find useful.

**Comment by buggins** [comment]
could you please send PR for fixing travis CI?

**Comment by SingingBush** [comment]
done a PR for this

**Pull request merged**
